apiVersion: v1
kind: Namespace
metadata:
  namespace: kubetest

---

apiVersion: v1   
kind: ConfigMap
metadata:
  namespace: kubtest
  name: kubetest-config
data:
  DEBUG: 1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namspace: kubtest
  name: kubetest-deployment
  labels:
    app: kubetest-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kubetest-app
        tier: kubetest-api
      spec:
        containers:
          - name: kubetest-app-container
            image: rohitchormale/kubetest:latest
            ports:
              - name: http
                protocol: HTTP
                containerPort: 8000
            envFrom:
              - configMapRef:
                name: kubetest-config
            livenessProbe:
              httpGet:
                scheme: HTTP
                path: /liveness
                port: 8000
              initialDelaySeconds: 16
              timeoutSeconds: 30
            # securityContext:
            #   allowPrivilegeEscalation: false
            #   readOnlyRootFilesystem: true
            #   runAsUser: 1001
            #   runAsGroup: 2001
              
---

apiVersion: v1
kind: Service
metadata:
  namespace: kubetest
  name: kubetest-service
  labels:
    app: kubetest-app
    tier: kubetest-api
spec:
  type: NodePort
  ports:
    - port: 8000
  selecor:
    app: kubetest-app
    tier: kubetest-api

