apiVersion: v1
kind: Namespace
metadata:
  name: probeservice

---

apiVersion: v1   
kind: ConfigMap
metadata:
  namespace: probeservice
  name: kubetest-config
data:
  DEBUG: "1"

---

# Deployment scenario
# Both Liveness and Readiness Endpoints will return 200 OK


apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: probeservice
  name: kubetest-deployment
  labels:
    app: kubetest-app
spec:
  selector:
    matchLabels:
      app: kubetest-app
      tier: kubetest-api
  replicas: 2
  template:
    metadata:
      labels:
        app: kubetest-app
        tier: kubetest-api
    spec:
      containers:
        - name: kubetest-container
          image: rohitchormale/kubetest:probeservice
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 8000
          envFrom:
          - configMapRef:
              name: kubetest-config
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /liveness
              port: 8000
            initialDelaySeconds: 16
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /readiness
              port: 8000
            initialDelaySeconds: 16
            periodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  namespace: probeservice
  name: kubetest-service
  labels:
    app: kubetest-app
    tier: kubetest-api
spec:
  type: NodePort
  ports:
    - port: 8000
  selector:
    app: kubetest-app
    tier: kubetest-api

